# Generated by Django 3.2.7 on 2021-09-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mood_journal', '0002_auto_20210911_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mood_journal.profile'),
        ),
    ]
