# Generated by Django 3.2.7 on 2021-09-11 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_journal', '0003_alter_mood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='link',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mood',
            name='status',
            field=models.TextField(blank=True, help_text='Tell me how you are feeling!', max_length=200),
        ),
        migrations.AlterField(
            model_name='mood',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
