# Generated by Django 3.2.7 on 2021-09-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_journal', '0004_auto_20210911_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='status',
            field=models.CharField(blank=True, help_text='Tell me how you are feeling!', max_length=200),
        ),
    ]
