# Generated by Django 3.2.7 on 2021-09-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_journal', '0005_alter_mood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='link_title',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
